version: '2'


services:
  mysql:
    container_name: problemManage-db
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@123123abc"
      MYSQL_DATABASE: "problemdb"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - kong-net
    ports:
      - "4004:3306"
  nodejs:
    hostname: problemManageService
    container_name: problemManage-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - kong-net

networks:
  kong-net:
    external: true