version: '2'


services:
  mysql:
    container_name: authen-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@123123abc"
      MYSQL_DATABASE: "testdb"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
    networks:
      - kong-net
  nodejs:
    hostname: authenservice
    container_name: authen-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - kong-net

networks:
  kong-net:
    external: true